FROM node:20-bookworm-slim

WORKDIR /app

RUN npm install -g npm@11.12.0

COPY package.json package-lock.json ./
COPY apps/backend/package.json apps/backend/package.json
COPY apps/storefront/package.json apps/storefront/package.json

RUN npm ci

COPY apps/backend apps/backend

WORKDIR /app/apps/backend

RUN npm run build

EXPOSE 9000

WORKDIR /app/apps/backend/.medusa/server

CMD ["npx", "medusa", "start"]
